In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
p = np.array([5, 1, 4, 6, 2, 4])
q1 = p
q2 = np.array([3, 7, 1, 4, 1, 6])
q3 = np.array([2, 5, 7, 2, 1, 5])

Calculating cross entropy loss function H(p, q) for p and q1, q2 and q3

In [3]:
-sum(p*np.log(q1))

-31.27439562761785

In [4]:
-sum(p*np.log(q2))

-22.923775636027425

In [5]:
-sum(p*np.log(q3))

-23.455449144551153

H(p, q) = -sum(p*np.log(q)) is smallest when p = q1

Turns out that the set of numbers that minimizes this is exactly q = p (Can be proven mathematically)

In [6]:
p = np.zeros(10, dtype = int); p[4] = 1
q = np.random.rand(10)
q = q/sum(q)

In [7]:
q

array([0.20066065, 0.1618995 , 0.09849327, 0.05287671, 0.05147106,
       0.13949833, 0.0199405 , 0.11577845, 0.00414178, 0.15523975])

In the case where it is known which class an image belongs to:

In [8]:
H = -np.log(q[p>0])
H

array([2.96673563])

In [9]:
q[4] = 20
q = q/sum(q) #Renormalize
H = -np.log(q[p>0])
H

array([0.04633615])

For Multiple images

In [11]:
p = np.zeros((4, 10), dtype = int)
p[0][4] = 1
p[1][2] = 1
p[2][8] = 1
p[3][6] =1

In [12]:
p

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

Create probability array of qs

In [13]:
q = np.random.rand(40).reshape(4, 10)
q = q/np.expand_dims(np.sum(q, axis = 1), axis = 1)

In [14]:
q

array([[0.16898015, 0.12445892, 0.20433488, 0.1416696 , 0.01045573,
        0.14396776, 0.05678886, 0.07449277, 0.0431122 , 0.03173912],
       [0.16767361, 0.02246019, 0.17170442, 0.04254701, 0.09838289,
        0.06569772, 0.03763339, 0.11554229, 0.15227739, 0.1260811 ],
       [0.18641958, 0.03563994, 0.15140379, 0.12017544, 0.10447797,
        0.12573531, 0.0733218 , 0.03558138, 0.1493378 , 0.01790699],
       [0.00899391, 0.02437164, 0.16657016, 0.06602902, 0.06017221,
        0.02617485, 0.10351487, 0.20037627, 0.24714809, 0.09664898]])

In [15]:
q[p>0]

array([0.01045573, 0.17170442, 0.1493378 , 0.10351487])

In [16]:
Hs = -np.log(q[p>0])
L = sum(Hs)

In [17]:
Hs

array([4.56060483, 1.76198076, 1.90154439, 2.26804002])

In [18]:
L

10.492170005028239

In [19]:
yhat = 20*np.random.rand(40).reshape(4,10) **2
yhat

array([[5.79166896e-01, 5.37161807e+00, 5.81618336e-02, 2.90399179e+00,
        7.39780499e-01, 1.31941444e+00, 2.42389166e+00, 2.61674789e+00,
        1.03668220e+01, 1.56901512e+00],
       [4.81499619e+00, 9.39216287e-03, 1.13054522e+01, 4.95142929e-01,
        4.38844702e-01, 1.09270480e+01, 1.94507768e+01, 1.32043508e+00,
        1.60642829e+01, 2.87530288e-01],
       [7.02323803e+00, 3.70702287e+00, 1.23235747e+01, 1.78236688e+01,
        2.00617098e+00, 1.73198734e+01, 6.71487325e+00, 1.15902808e+00,
        4.43368573e+00, 1.29227574e+01],
       [1.27222844e+01, 3.07409480e+00, 3.74042583e+00, 1.24971292e+01,
        1.76212424e+01, 1.04590155e+01, 1.27367985e+01, 3.55501922e-02,
        3.42970190e+00, 7.35945459e+00]])

In [20]:
q = np.exp(yhat)
q

array([[1.78455110e+00, 2.15210813e+02, 1.05988651e+00, 1.82468377e+01,
        2.09547550e+00, 3.74123000e+00, 1.12897096e+01, 1.36911261e+01,
        3.17872958e+04, 4.80191657e+00],
       [1.23346342e+02, 1.00943641e+00, 8.12635007e+04, 1.64073273e+00,
        1.55091441e+00, 5.56617210e+04, 2.80133480e+08, 3.74505041e+00,
        9.47609574e+06, 1.33313097e+00],
       [1.12241515e+03, 4.07323601e+01, 2.24936786e+05, 5.50453986e+07,
        7.43479477e+00, 3.32602460e+07, 8.24579244e+02, 3.18683441e+00,
        8.42413366e+01, 4.09526716e+05],
       [3.35133566e+05, 2.16302933e+01, 4.21159206e+01, 2.67568060e+05,
        4.49581406e+07, 3.48572178e+04, 3.40033202e+05, 1.03618966e+00,
        3.08674398e+01, 1.57097950e+03]])

In [21]:
q = q/np.expand_dims(np.sum(q, axis = 1), axis = 1)

In [22]:
q.sum(axis = 1)

array([1., 1., 1., 1.])

In [23]:
c_squiq = np.where(p)
c_squiq

(array([0, 1, 2, 3], dtype=int64), array([4, 2, 8, 6], dtype=int64))

In [24]:
q[c_squiq]

array([6.53626532e-05, 2.80464003e-04, 9.47147084e-07, 7.40209954e-03])

In [25]:
Hs = -np.log(q[c_squiq])
L = sum(Hs)
L

36.59042772407631

Proof this is equivalent to Pytorch

In [26]:
L = torch.nn.CrossEntropyLoss(reduction = 'sum')

Evaluate on data above

In [27]:
L(torch.tensor(yhat), torch.tensor(p, dtype = torch.float))

tensor(36.5904, dtype=torch.float64)