In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [3]:
p = np.array([5, 1, 4, 6, 2, 4])
q1 = p
q2 = np.array([3, 7, 1, 4, 1, 6])
q3 = np.array([2, 5, 7, 2, 1, 5])

Calculating cross entropy loss function H(p, q) for p and q1, q2 and q3

In [ ]:
-sum(p*np.log(q1))

-31.27439562761785

In [5]:
-sum(p*np.log(q2))

-22.923775636027425

In [6]:
-sum(p*np.log(q3))

-23.455449144551153

H(p, q) = -sum(p*np.log(q)) is smallest when p = q1

Turns out that the set of numbers that minimizes this is exactly q = p (Can be proven mathematically)

In [7]:
p = np.zeros(10, dtype = int); p[4] = 1
q = np.random.rand(10)
q = q/sum(q)

In [8]:
q

array([0.09606191, 0.04368457, 0.04649018, 0.10262508, 0.11025811,
       0.05315672, 0.16526241, 0.11429686, 0.12431288, 0.14385129])

In the case where it is known which class an image belongs to:

In [9]:
H = -np.log(q[p>0])
H

array([2.20493122])

In [10]:
q[4] = 20
q = q/sum(q) #Renormalize
H = -np.log(q[p>0])
H

array([0.04352595])