In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time

Pytorch is a python package that is used to train state-of-the-art machine learning/deep learning models.

Pytorch Tensors

In [2]:
# A pytorch tensor can be create the same as a numpy array

t = torch.linspace(0, 1, 5)
t

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [3]:
# Can also be reshaped in the same way

t = torch.arange(48).reshape(3, 4, 4)
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]])

Most importantly, tensors have the same broadcasting rules as numpy arrays.

In [4]:
a = torch.ones((6, 5))
b = torch.arange(5).reshape(1,5)

In [5]:
a + b

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

In [6]:
scale = torch.tensor([0.5, 1.5, 1])
scale

tensor([0.5000, 1.5000, 1.0000])

In [7]:
image = torch.randn([256, 256, 3])

In [8]:
result = image * scale

In [9]:
result

tensor([[[ 0.5059, -1.3471,  0.6298],
         [ 0.4349, -0.2015, -0.1095],
         [-0.1384,  0.7258, -0.8637],
         ...,
         [-0.9593, -0.3827,  0.9455],
         [-0.0135,  2.0395,  0.7903],
         [-0.0504,  1.5740,  0.0418]],

        [[-0.2224,  0.0193,  0.0893],
         [-0.4687, -2.2356,  1.0720],
         [-0.5889,  0.1125,  1.9481],
         ...,
         [ 0.2645,  0.0753,  0.1926],
         [-0.1522, -0.3317, -0.4632],
         [ 0.2585, -0.9094, -0.7029]],

        [[ 0.4467,  1.6325, -0.0753],
         [-0.3028,  0.4131, -0.5404],
         [-0.0900, -2.0233,  0.2328],
         ...,
         [-0.7718, -1.4381, -1.3289],
         [ 0.2067, -0.9360,  1.5179],
         [-0.1955, -0.5443, -0.5314]],

        ...,

        [[ 0.4906, -4.3009, -1.0802],
         [-0.3649,  0.1743,  0.2394],
         [-0.1949, -1.6880,  1.8116],
         ...,
         [-0.7946,  0.0295, -2.0789],
         [-0.8889,  1.1046, -0.5848],
         [-0.1648, -2.0114, -0.1500]],

        [[

In [10]:
images = torch.randn([2, 256, 256, 3])
scales = torch.tensor([0.5, 1.5, 1, 1.5, 1, 0.5]).reshape(2, 1, 1, 3)

In [11]:
scales

tensor([[[[0.5000, 1.5000, 1.0000]]],


        [[[1.5000, 1.0000, 0.5000]]]])

In [12]:
results = images * scales

In [13]:
images.shape

torch.Size([2, 256, 256, 3])

In [14]:
t = torch.tensor([0.5, 1, 3, 4])
torch.mean(t), torch.std(t), torch.min(t), torch.max(t)

(tensor(2.1250), tensor(1.6520), tensor(0.5000), tensor(4.))

In [15]:
t = torch.arange(20, dtype = float).reshape(5, 4)

In [16]:
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=torch.float64)

In [17]:
torch.mean(t, axis = 0)

tensor([ 8.,  9., 10., 11.], dtype=torch.float64)

In [18]:
t = torch.rand(5, 256, 256, 3)

In [19]:
torch.mean(t, axis = 0)

tensor([[[0.5210, 0.3757, 0.3115],
         [0.5037, 0.6305, 0.3764],
         [0.4382, 0.3970, 0.6924],
         ...,
         [0.5839, 0.3415, 0.6683],
         [0.5209, 0.4540, 0.3167],
         [0.4845, 0.6809, 0.4501]],

        [[0.5195, 0.6163, 0.5202],
         [0.5133, 0.3769, 0.3706],
         [0.1610, 0.4751, 0.5373],
         ...,
         [0.3563, 0.5509, 0.5320],
         [0.4976, 0.6541, 0.4792],
         [0.4239, 0.6519, 0.6137]],

        [[0.3105, 0.6782, 0.3461],
         [0.5038, 0.4394, 0.5277],
         [0.4345, 0.4713, 0.5199],
         ...,
         [0.5957, 0.4993, 0.6024],
         [0.4282, 0.7377, 0.6205],
         [0.4381, 0.6546, 0.4193]],

        ...,

        [[0.4035, 0.3186, 0.5238],
         [0.4434, 0.4003, 0.5756],
         [0.8025, 0.5279, 0.5527],
         ...,
         [0.7490, 0.4714, 0.4628],
         [0.5616, 0.3106, 0.5618],
         [0.4746, 0.6911, 0.6700]],

        [[0.3408, 0.5817, 0.3776],
         [0.4460, 0.4437, 0.5580],
         [0.

In [20]:
torch.mean(t, axis = -1)

tensor([[[0.2747, 0.7669, 0.4675,  ..., 0.5757, 0.6842, 0.7201],
         [0.5820, 0.2898, 0.2641,  ..., 0.3039, 0.4181, 0.7850],
         [0.3140, 0.5726, 0.5720,  ..., 0.4162, 0.7396, 0.4841],
         ...,
         [0.7266, 0.5844, 0.6152,  ..., 0.5536, 0.6537, 0.8864],
         [0.5834, 0.4030, 0.5341,  ..., 0.7219, 0.3107, 0.4762],
         [0.1907, 0.4511, 0.1645,  ..., 0.6108, 0.7551, 0.7165]],

        [[0.3441, 0.3988, 0.5777,  ..., 0.3626, 0.3195, 0.4004],
         [0.6056, 0.8426, 0.1958,  ..., 0.4073, 0.5503, 0.5965],
         [0.5466, 0.6086, 0.6730,  ..., 0.6534, 0.6172, 0.6471],
         ...,
         [0.1241, 0.5957, 0.4992,  ..., 0.6923, 0.6946, 0.7104],
         [0.2223, 0.3498, 0.3660,  ..., 0.6155, 0.7649, 0.3879],
         [0.9034, 0.2936, 0.7023,  ..., 0.5950, 0.5263, 0.5836]],

        [[0.8542, 0.2605, 0.4552,  ..., 0.4494, 0.2846, 0.4442],
         [0.7906, 0.3684, 0.3032,  ..., 0.3146, 0.6659, 0.5150],
         [0.4305, 0.7645, 0.0885,  ..., 0.6662, 0.5570, 0.

In [21]:
# Returns the value of the max and its index
values, indices = torch.max(t, axis = -1)

Torch Starts to differ from Numpy in terms of automatically computing gradient of operations

In [22]:
x = torch.tensor([[5., 8.], [4., 6.]], requires_grad = True)
x

tensor([[5., 8.],
        [4., 6.]], requires_grad=True)

In [23]:
y = x.pow(3).sum()
y

tensor(917., grad_fn=<SumBackward0>)

Compute the gradient:

In [24]:
y.backward() #Compute the gradient
x.grad #Print the gradient (Everything that has happened to x)

tensor([[ 75., 192.],
        [ 48., 108.]])

Double check using the analytical formula (3x^2):

In [25]:
3*x**2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)

Pytorch is also faster for matrix multiplication than numpy

Using pytorch:

In [31]:
A = torch.randn(1000, 1000)
B = torch.randn(1000, 1000)

In [32]:
t1 = time.perf_counter()
torch.matmul(A, B)
t2 = time.perf_counter()
print(t2 - t1)

0.02961880000293604


Using numpy:

In [33]:
A = np.random.randn(1000, 1000)
B = np.random.randn(1000, 1000)

In [34]:
t1 = time.perf_counter()
A@B
t2 = time.perf_counter()
print(t2 - t1)

3.3718985999985307
